import type { NextConfig } from "next";

/**
 * Permanent redirects preserving the old bearteam.com site's indexed URLs
 * (151-URL inventory from the pre-cutover audit, 2026-08-28). The old
 * /testimonials URL is not redirected: the new site now serves a real
 * /testimonials page at the same address. Old IDX listing pages (/idx/...)
 * are not enumerable and get a pattern redirect. Test every redirect on the
 * preview deploy before DNS cutover — see DOMAIN_CUTOVER.md.
 */
const legacyRedirects = [
    { source: "/mortgage-rates", destination: "/resources/financing-preparation", permanent: true },
    { source: "/featured-listings", destination: "/listings", permanent: true },
    { source: "/quick-search-legacy", destination: "/search", permanent: true },
    { source: "/advanced-search-legacy", destination: "/search", permanent: true },
    { source: "/map-search", destination: "/search", permanent: true },
    { source: "/foreclosure-search-legacy", destination: "/search", permanent: true },
    { source: "/commercial-search-legacy", destination: "/search", permanent: true },
    { source: "/search-by-area", destination: "/search", permanent: true },
    { source: "/quick-search", destination: "/search", permanent: true },
    { source: "/advanced-search", destination: "/search", permanent: true },
    { source: "/foreclosure-search", destination: "/search", permanent: true },
    { source: "/about-us", destination: "/about", permanent: true },
    { source: "/contact-us", destination: "/contact", permanent: true },
    { source: "/newsletter", destination: "/contact", permanent: true },
    { source: "/dream-home-finder", destination: "/buy", permanent: true },
    { source: "/free-market-analysis", destination: "/home-value", permanent: true },
    { source: "/real-estate-glossary", destination: "/resources", permanent: true },
    { source: "/where-does-the-money-come-from-for-mortgage-loans", destination: "/resources", permanent: true },
    { source: "/lead-poisoning", destination: "/resources", permanent: true },
    { source: "/plan-of-action", destination: "/resources", permanent: true },
    { source: "/is-buying-a-home-still-a-smart-plan", destination: "/resources", permanent: true },
    { source: "/the-biweekly-mortgage-who-needs-it", destination: "/resources", permanent: true },
    { source: "/title-insurance-when-refinancing-your-loan", destination: "/resources", permanent: true },
    { source: "/underground-heating-oil-tanks", destination: "/resources", permanent: true },
    { source: "/for-sale-by-owner-a-good-idea", destination: "/resources", permanent: true },
    { source: "/hot-normal-and-cold-markets", destination: "/resources", permanent: true },
    { source: "/land-contract", destination: "/resources", permanent: true },
    { source: "/title-insurance-requirements-for-insuring-trusts", destination: "/resources", permanent: true },
    { source: "/living-trusts", destination: "/resources", permanent: true },
    { source: "/insist-on-a-home-inspection", destination: "/resources", permanent: true },
    { source: "/avoiding-financial-stress", destination: "/resources", permanent: true },
    { source: "/the-no-cost-thirty-year-fixed-rate-mortgage", destination: "/resources", permanent: true },
    { source: "/title-insurance-where-does-your-dollar-go", destination: "/resources", permanent: true },
    { source: "/environmental-issues", destination: "/resources", permanent: true },
    { source: "/finding-the-right-agent", destination: "/resources", permanent: true },
    { source: "/finding-the-right-seller", destination: "/resources", permanent: true },
    { source: "/which-arm-is-the-best-alternative", destination: "/resources", permanent: true },
    { source: "/understanding-title-insurance", destination: "/resources", permanent: true },
    { source: "/condominium-and-pud-ownership", destination: "/resources", permanent: true },
    { source: "/making-a-good-first-impression", destination: "/resources", permanent: true },
    { source: "/use-a-buyers-agent", destination: "/resources", permanent: true },
    { source: "/the-advantages-of-different-types-of-mortgage-lenders", destination: "/resources", permanent: true },
    { source: "/creative-financing", destination: "/resources", permanent: true },
    { source: "/mechanics-liens", destination: "/resources", permanent: true },
    { source: "/know-why-you-are-selling", destination: "/resources", permanent: true },
    { source: "/why-you-should-not-make-any-major-credit-purchases", destination: "/resources", permanent: true },
    { source: "/whats-a-fico", destination: "/resources", permanent: true },
    { source: "/statements-of-information", destination: "/resources", permanent: true },
    { source: "/considering-offers", destination: "/resources", permanent: true },
    { source: "/build-a-plan-of-action-and-get-ready", destination: "/resources", permanent: true },
    { source: "/types-of-mortgage-lenders", destination: "/resources", permanent: true },
    { source: "/understanding-preliminary-reports", destination: "/resources", permanent: true },
    { source: "/setting-the-price", destination: "/resources", permanent: true },
    { source: "/importance-of-inspection", destination: "/resources", permanent: true },
    { source: "/your-savings-and-down-payment", destination: "/resources", permanent: true },
    { source: "/items-you-need-when-applying-for-a-loan", destination: "/resources", permanent: true },
    { source: "/why-do-you-need-title-insurance", destination: "/resources", permanent: true },
    { source: "/the-functions-of-an-escrow", destination: "/resources", permanent: true },
    { source: "/required-reporting-to-the-irs", destination: "/resources", permanent: true },
    { source: "/understanding-foreclosures", destination: "/resources", permanent: true },
    { source: "/common-ways-of-holding-title", destination: "/resources", permanent: true },
    { source: "/what-is-a-short-sale-anyway", destination: "/resources", permanent: true },
    { source: "/getting-the-highest-price-in-the-shortest-time", destination: "/resources", permanent: true },
    { source: "/thinking-about-buying-a-foreclosure", destination: "/resources", permanent: true },
    { source: "/getting-a-legitimate-lender-and-getting-pre-approved", destination: "/resources", permanent: true },
    { source: "/relocation-1", destination: "/relocation", permanent: true },
    { source: "/homes-for-sale-in-conway-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-conway-orlando-fl-under-300000", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-conway-orlando-fl-300000-to-400000", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-conway-orlando-fl-400000-to-500000", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-conway-orlando-fl-500000-to-700000", destination: "/communities/conway", permanent: true },
    { source: "/luxury-homes-for-sale-in-conway-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/condos-for-sale-in-conway-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/new-construction-homes-for-sale-in-conway-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/homes-with-a-pool-for-sale-in-conway-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-lake-holden-grove-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-lake-holden-grove-orlando-fl-under-300000", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-lake-holden-grove-orlando-fl-300000-to-400000", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-lake-holden-grove-orlando-fl-400000-to-500000", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-lake-holden-grove-orlando-fl-500000-to-700000", destination: "/communities/conway", permanent: true },
    { source: "/luxury-homes-for-sale-in-lake-holden-grove-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/condos-for-sale-in-lake-holden-grove-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/new-construction-homes-for-sale-in-lake-holden-grove-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/homes-with-a-pool-for-sale-in-lake-holden-grove-orlando-fl", destination: "/communities/conway", permanent: true },
    { source: "/conway-homes", destination: "/communities/conway", permanent: true },
    { source: "/lake-holden-grove-homes", destination: "/communities/conway", permanent: true },
    { source: "/homes-for-sale-in-downtown-orlando-orlando-fl", destination: "/communities/orlando", permanent: true },
    { source: "/homes-for-sale-in-downtown-orlando-orlando-fl-under-300000", destination: "/communities/orlando", permanent: true },
    { source: "/homes-for-sale-in-downtown-orlando-orlando-fl-300000-to-400000", destination: "/communities/orlando", permanent: true },
    { source: "/homes-for-sale-in-downtown-orlando-orlando-fl-400000-to-500000", destination: "/communities/orlando", permanent: true },
    { source: "/homes-for-sale-in-downtown-orlando-orlando-fl-500000-to-700000", destination: "/communities/orlando", permanent: true },
    { source: "/luxury-homes-for-sale-in-downtown-orlando-orlando-fl", destination: "/communities/orlando", permanent: true },
    { source: "/condos-for-sale-in-downtown-orlando-orlando-fl", destination: "/communities/orlando", permanent: true },
    { source: "/new-construction-homes-for-sale-in-downtown-orlando-orlando-fl", destination: "/communities/orlando", permanent: true },
    { source: "/homes-with-a-pool-for-sale-in-downtown-orlando-orlando-fl", destination: "/communities/orlando", permanent: true },
    { source: "/downtown-orlando-homes", destination: "/communities/orlando", permanent: true },
    { source: "/homes-for-sale-in-baldwin-park-orlando-fl", destination: "/communities/baldwin-park", permanent: true },
    { source: "/homes-for-sale-in-baldwin-park-orlando-fl-under-300000", destination: "/communities/baldwin-park", permanent: true },
    { source: "/homes-for-sale-in-baldwin-park-orlando-fl-300000-to-400000", destination: "/communities/baldwin-park", permanent: true },
    { source: "/homes-for-sale-in-baldwin-park-orlando-fl-400000-to-500000", destination: "/communities/baldwin-park", permanent: true },
    { source: "/homes-for-sale-in-baldwin-park-orlando-fl-500000-to-700000", destination: "/communities/baldwin-park", permanent: true },
    { source: "/luxury-homes-for-sale-in-baldwin-park-orlando-fl", destination: "/communities/baldwin-park", permanent: true },
    { source: "/condos-for-sale-in-baldwin-park-orlando-fl", destination: "/communities/baldwin-park", permanent: true },
    { source: "/new-construction-homes-for-sale-in-baldwin-park-orlando-fl", destination: "/communities/baldwin-park", permanent: true },
    { source: "/homes-with-a-pool-for-sale-in-baldwin-park-orlando-fl", destination: "/communities/baldwin-park", permanent: true },
    { source: "/baldwin-park-homes", destination: "/communities/baldwin-park", permanent: true },
    { source: "/homes-for-sale-in-pine-castle-orlando-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-pine-castle-orlando-fl-under-300000", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-pine-castle-orlando-fl-300000-to-400000", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-pine-castle-orlando-fl-400000-to-500000", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-pine-castle-orlando-fl-500000-to-700000", destination: "/communities/belle-isle", permanent: true },
    { source: "/luxury-homes-for-sale-in-pine-castle-orlando-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/condos-for-sale-in-pine-castle-orlando-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/new-construction-homes-for-sale-in-pine-castle-orlando-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-with-a-pool-for-sale-in-pine-castle-orlando-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-belle-isle-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-belle-isle-fl-under-300000", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-belle-isle-fl-300000-to-400000", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-belle-isle-fl-400000-to-500000", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-belle-isle-fl-500000-to-700000", destination: "/communities/belle-isle", permanent: true },
    { source: "/luxury-homes-for-sale-in-belle-isle-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/condos-for-sale-in-belle-isle-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/new-construction-homes-for-sale-in-belle-isle-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-with-a-pool-for-sale-in-belle-isle-fl", destination: "/communities/belle-isle", permanent: true },
    { source: "/belle-isle-homes", destination: "/communities/belle-isle", permanent: true },
    { source: "/pine-castle-homes", destination: "/communities/belle-isle", permanent: true },
    { source: "/homes-for-sale-in-edgewood-fl", destination: "/communities/edgewood", permanent: true },
    { source: "/homes-for-sale-in-edgewood-fl-under-300000", destination: "/communities/edgewood", permanent: true },
    { source: "/homes-for-sale-in-edgewood-fl-300000-to-400000", destination: "/communities/edgewood", permanent: true },
    { source: "/homes-for-sale-in-edgewood-fl-400000-to-500000", destination: "/communities/edgewood", permanent: true },
    { source: "/homes-for-sale-in-edgewood-fl-500000-to-700000", destination: "/communities/edgewood", permanent: true },
    { source: "/luxury-homes-for-sale-in-edgewood-fl", destination: "/communities/edgewood", permanent: true },
    { source: "/condos-for-sale-in-edgewood-fl", destination: "/communities/edgewood", permanent: true },
    { source: "/new-construction-homes-for-sale-in-edgewood-fl", destination: "/communities/edgewood", permanent: true },
    { source: "/homes-with-a-pool-for-sale-in-edgewood-fl", destination: "/communities/edgewood", permanent: true },
    { source: "/edgewood-homes", destination: "/communities/edgewood", permanent: true },
    { source: "/homes-for-sale-in-lake-nona-orlando-fl", destination: "/communities/lake-nona", permanent: true },
    { source: "/homes-for-sale-in-lake-nona-orlando-fl-under-300000", destination: "/communities/lake-nona", permanent: true },
    { source: "/homes-for-sale-in-lake-nona-orlando-fl-300000-to-400000", destination: "/communities/lake-nona", permanent: true },
    { source: "/homes-for-sale-in-lake-nona-orlando-fl-400000-to-500000", destination: "/communities/lake-nona", permanent: true },
    { source: "/homes-for-sale-in-lake-nona-orlando-fl-500000-to-700000", destination: "/communities/lake-nona", permanent: true },
    { source: "/luxury-homes-for-sale-in-lake-nona-orlando-fl", destination: "/communities/lake-nona", permanent: true },
    { source: "/condos-for-sale-in-lake-nona-orlando-fl", destination: "/communities/lake-nona", permanent: true },
    { source: "/new-construction-homes-for-sale-in-lake-nona-orlando-fl", destination: "/communities/lake-nona", permanent: true },
    { source: "/homes-with-a-pool-for-sale-in-lake-nona-orlando-fl", destination: "/communities/lake-nona", permanent: true },
    { source: "/lake-nona-homes", destination: "/communities/lake-nona", permanent: true },
    { source: "/our-team", destination: "/team", permanent: true },
    { source: "/welcome-to-my-new-website", destination: "/blog", permanent: true },
    { source: "/idx/:path*", destination: "/search", permanent: true },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  images: {
    // Stellar MLS listing photos via MLS Grid (listings_source = 'mls').
    remotePatterns: [{ protocol: "https", hostname: "s3.amazonaws.com", pathname: "/mlsgrid/**" }],
  },
  async redirects() {
    return legacyRedirects;
  },
};

export default nextConfig;
