import type { Metadata } from "next";
import { siteConfig } from "@/config/site";

type PageMeta = {
  title: string;
  description: string;
  path: string;
  ogTitle?: string;
};

/**
 * Builds consistent per-page metadata: unique title/description, canonical
 * URL, Open Graph, and Twitter card data. The OG image is generated by
 * app/opengraph-image.tsx.
 */
export function buildMetadata({ title, description, path, ogTitle }: PageMeta): Metadata {
  const url = `${siteConfig.url}${path}`;
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title: ogTitle ?? title,
      description,
      url,
      siteName: siteConfig.name,
      locale: "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle ?? title,
      description,
    },
  };
}
